/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PWDBReader */

#ifndef _Included_PWDBReader
#define _Included_PWDBReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PWDBReader
 * Method:    getpwent
 * Signature: ()LPW;
 */
JNIEXPORT jobject JNICALL Java_PWDBReader_getpwent
  (JNIEnv *, jobject);

/*
 * Class:     PWDBReader
 * Method:    getpwnam
 * Signature: (Ljava/lang/String;)LPW;
 */
JNIEXPORT jobject JNICALL Java_PWDBReader_getpwnam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PWDBReader
 * Method:    getpwuid
 * Signature: (I)LPW;
 */
JNIEXPORT jobject JNICALL Java_PWDBReader_getpwuid
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
